package codegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/flowrule/flowrule/internal/domain"
)

type Generator struct {
	schema *domain.ContractSchema
}

func NewGenerator(schema *domain.ContractSchema) *Generator {
	return &Generator{schema: schema}
}

func (g *Generator) GenerateGo(outputDir string) ([]string, error) {
	return g.generate(outputDir, "go", goTemplate, ".go")
}

func (g *Generator) GenerateJava(outputDir string) ([]string, error) {
	return g.generate(outputDir, "java", javaTemplate, ".java")
}

func (g *Generator) GenerateProtobuf(outputDir string) ([]string, error) {
	return g.generate(outputDir, "protobuf", protobufTemplate, ".proto")
}

func (g *Generator) GenerateJSONSchema(outputDir string) ([]string, error) {
	return g.generate(outputDir, "jsonschema", jsonschemaTemplate, ".json")
}

func (g *Generator) generate(outputDir, subdir string, tmpl *template.Template, ext string) ([]string, error) {
	dir := filepath.Join(outputDir, subdir)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("create output dir: %w", err)
	}

	typeName := toPascalCase(g.schema.Name)
	fileName := strings.ToLower(typeName) + ext
	filePath := filepath.Join(dir, fileName)

	f, err := os.Create(filePath)
	if err != nil {
		return nil, fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	data := struct {
		Schema        *domain.ContractSchema
		TypeName      string
		PackageName   string
		Namespace     string
		Fields        []FieldInfo
	}{
		Schema:      g.schema,
		TypeName:    typeName,
		PackageName: strings.ToLower(g.schema.Name),
		Namespace:   g.schema.Namespace,
		Fields:      g.buildFields(),
	}

	if err := tmpl.Execute(f, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	return []string{filePath}, nil
}

type FieldInfo struct {
	Name        string
	GoType      string
	JavaType    string
	ProtoType   string
	JSONSchema  map[string]interface{}
	Required    bool
	Description string
}

func (g *Generator) buildFields() []FieldInfo {
	var fields []FieldInfo
	for name, field := range g.schema.Fields {
		f := FieldInfo{
			Name:        name,
			GoType:      g.mapGoType(field.Type),
			JavaType:    g.mapJavaType(field.Type),
			ProtoType:   g.mapProtoType(field.Type),
			JSONSchema:  g.mapJSONSchema(field),
			Required:    field.Required,
			Description: field.Description,
		}
		fields = append(fields, f)
	}
	return fields
}

func (g *Generator) mapGoType(t string) string {
	switch t {
	case "string":
		return "string"
	case "integer", "int", "int64":
		return "int64"
	case "number", "float", "double":
		return "float64"
	case "boolean", "bool":
		return "bool"
	case "object":
		return "map[string]interface{}"
	case "array":
		return "[]interface{}"
	default:
		return "interface{}"
	}
}

func (g *Generator) mapJavaType(t string) string {
	switch t {
	case "string":
		return "String"
	case "integer", "int", "int64":
		return "Long"
	case "number", "float", "double":
		return "Double"
	case "boolean", "bool":
		return "Boolean"
	case "object":
		return "Map<String, Object>"
	case "array":
		return "List<Object>"
	default:
		return "Object"
	}
}

func (g *Generator) mapProtoType(t string) string {
	switch t {
	case "string":
		return "string"
	case "integer", "int", "int64":
		return "int64"
	case "number", "float", "double":
		return "double"
	case "boolean", "bool":
		return "bool"
	case "object":
		return "google.protobuf.Struct"
	case "array":
		return "repeated google.protobuf.Value"
	default:
		return "string"
	}
}

func (g *Generator) mapJSONSchema(field domain.ContractField) map[string]interface{} {
	schema := map[string]interface{}{
		"type": field.Type,
	}
	if field.Description != "" {
		schema["description"] = field.Description
	}
	if field.Format != "" {
		schema["format"] = field.Format
	}
	if field.Enum != nil && len(field.Enum) > 0 {
		schema["enum"] = field.Enum
	}
	if field.Default != nil {
		schema["default"] = field.Default
	}
	if field.Items != nil {
		schema["items"] = field.Items
	}
	if field.Properties != nil {
		props := make(map[string]interface{})
		for k, v := range field.Properties {
			props[k] = g.mapJSONSchema(v)
		}
		schema["properties"] = props
	}
	return schema
}

func toPascalCase(s string) string {
	parts := strings.Split(s, ".")
	last := parts[len(parts)-1]
	segments := strings.Split(last, "_")
	for i, seg := range segments {
		if len(seg) > 0 {
			segments[i] = strings.ToUpper(seg[:1]) + seg[1:]
		}
	}
	return strings.Join(segments, "")
}

var goTemplate = template.Must(template.New("go").Parse(`// Code generated by FlowRule. DO NOT EDIT.

package {{.PackageName}}

{{if .Schema.Description}}// {{.Schema.Description}}
{{end}}// {{.TypeName}} represents the {{.Schema.Name}} contract v{{.Schema.Version}}
type {{.TypeName}} struct {
{{- range .Fields}}
	{{.Name}} {{.GoType}} ` + "`" + `json:"{{.Name}}"` + "`" + `
{{- end}}
}
`))

var javaTemplate = template.Must(template.New("java").Parse(`// Code generated by FlowRule. DO NOT EDIT.

package {{.PackageName}};

import com.fasterxml.jackson.annotation.JsonProperty;
{{if .Schema.Description}}/**
 * {{.Schema.Description}}
 */
{{end}}public class {{.TypeName}} {
{{- range .Fields}}
    @JsonProperty("{{.Name}}")
    private {{.JavaType}} {{.Name}};
{{- end}}

    // Getters and setters
{{- range .Fields}}
    public {{.JavaType}} get{{.Name}}() {
        return {{.Name}};
    }

    public void set{{.Name}}({{.JavaType}} {{.Name}}) {
        this.{{.Name}} = {{.Name}};
    }
{{- end}}
}
`))

var protobufTemplate = template.Must(template.New("protobuf").Funcs(template.FuncMap{
	"add1": func(i int) int {
		return i + 1
	},
}).Parse(`// Code generated by FlowRule. DO NOT EDIT.

syntax = "proto3";

package {{.PackageName}};

option go_package = "{{.Namespace}}/{{.PackageName}}";

{{if .Schema.Description}}// {{.Schema.Description}}
{{end}}message {{.TypeName}} {
{{- range $i, $field := .Fields}}
    {{.ProtoType}} {{.Name}} = {{add1 $i}};
{{- end}}
}
`))

var jsonschemaTemplate = template.Must(template.New("jsonschema").Funcs(template.FuncMap{
	"toJSON": func(v interface{}) string {
		b, _ := json.MarshalIndent(v, "", "  ")
		return string(b)
	},
	"sub": func(a, b int) int {
		return a - b
	},
	"add1": func(i int) int {
		return i + 1
	},
}).Parse(`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://flowrule.io/schemas/{{.Schema.Name}}-v{{.Schema.Version}}.json",
  "title": "{{.Schema.Name}}",
  "type": "object",
  {{if .Schema.Description}}"description": "{{.Schema.Description}}",{{end}}
  "properties": {
{{- range $i, $field := .Fields}}
    "{{.Name}}": {{toJSON .JSONSchema}}{{if ne $i (sub (len $.Fields) 1)}},{{end}}
{{- end}}
  },
  "required": [
{{- range $i, $field := .Fields}}
    {{if .Required}}"{{.Name}}"{{if ne $i (sub (len $.Fields) 1)}},{{end}}{{end}}
{{- end}}
  ],
  "additionalProperties": false
}
`))