// Code generated by FlowRule. DO NOT EDIT.

package runtime

import (
	"context"
	"encoding/json"
	"time"

	"github.com/nats-io/nats.go/jetstream"
)

// HandlerFunc is the function signature for handling order.created events
type HandlerFunc func(ctx context.Context, payload *order_created.Created, envelope *Envelope) error

// Consumer handles consuming order.created events
type Consumer struct {
	js        jetstream.JetStream
	stream    string
	consumer  string
	handler   HandlerFunc
	numShards uint32
}

// NewConsumer creates a new consumer for order.created
func NewConsumer(js jetstream.JetStream, stream, consumer string, numShards uint32, handler HandlerFunc) *Consumer {
	return &Consumer{
		js:        js,
		stream:    stream,
		consumer:  consumer,
		handler:   handler,
		numShards: numShards,
	}
}

// Start begins consuming events
func (c *Consumer) Start(ctx context.Context) error {
	jsConsumer, err := c.js.Consumer(ctx, c.stream, c.consumer)
	if err != nil {
		return err
	}

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
			batch, err := jsConsumer.Fetch(10, jetstream.FetchMaxWait(5*time.Second))
			if err != nil {
				continue
			}

			for msg := range batch.Messages() {
				var env Envelope
				if err := json.Unmarshal(msg.Data(), &env); err != nil {
					msg.Nak()
					continue
				}

				payload, err := env.Payload()
				if err != nil {
					msg.Nak()
					continue
				}

				if err := c.handler(ctx, payload, &env); err != nil {
					msg.Nak()
					continue
				}

				msg.Ack()
			}
		}
	}
}
