// Code generated by FlowRule. DO NOT EDIT.

package runtime

import (
	"encoding/json"
	"time"

	"github.com/flowrule/flowrule/internal/domain"
)

// Envelope wraps a typed payload with metadata for event processing
type Envelope struct {
	ID           string            `json:"id"`
	Type         string            `json:"type"`
	TenantID     string            `json:"tenant_id"`
	PartitionKey string            `json:"partition_key"`
	WorkflowID   string            `json:"workflow_id,omitempty"`
	OccurredAt   time.Time         `json:"occurred_at"`
	Data         json.RawMessage   `json:"data"`
	Headers      map[string]string `json:"headers,omitempty"`
}

// NewEnvelope creates an envelope for the order.created event
func NewEnvelope(payload *order_created.Created, tenantID, partitionKey string) *Envelope {
	data, _ := json.Marshal(payload)
	return &Envelope{
		ID:           domain.NewID(),
		Type:         "order.created",
		TenantID:     tenantID,
		PartitionKey: partitionKey,
		OccurredAt:   time.Now().UTC(),
		Data:         data,
	}
}

// Payload unmarshals the envelope data into the typed payload
func (e *Envelope) Payload() (*order_created.Created, error) {
	var payload order_created.Created
	if err := json.Unmarshal(e.Data, &payload); err != nil {
		return nil, err
	}
	return &payload, nil
}

// Shard computes the virtual shard for this envelope
func (e *Envelope) Shard(numShards uint32) uint32 {
	return domain.ComputeShard(e.TenantID, e.PartitionKey, numShards)
}

// Marshal serializes the envelope to JSON
func (e *Envelope) Marshal() ([]byte, error) {
	return json.Marshal(e)
}
