// Code generated by FlowRule. DO NOT EDIT.

package runtime

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/flowrule/flowrule/internal/domain"
)

// Effect represents an effect to be emitted
type Effect struct {
	Type           string
	Payload        map[string]any
	PartitionKey   string
}

// Evaluator evaluates rules against a payload
type Evaluator struct {
	rules []CompiledRule
}

// CompiledRule is a pre-compiled rule for fast evaluation
type CompiledRule struct {
	ID        string
	Priority  int
	Condition ConditionFunc
	Effects   []EffectTemplate
}

// ConditionFunc evaluates a condition against payload
type ConditionFunc func(payload map[string]any) bool

// EffectTemplate defines an effect to emit with template substitution
type EffectTemplate struct {
	EventType           string
	PartitionKeyPolicy  string
	DataTemplate        map[string]string
}

// NewEvaluator creates a new evaluator with compiled rules
func NewEvaluator() *Evaluator {
	return &Evaluator{
		rules: []CompiledRule{
			{
				ID:       "payment_required",
				Priority: 100,
				Condition: func(payload map[string]any) bool {
					val, ok := getFloat64(payload, "total_amount"); ok && val > 0
				},
				Effects: []EffectTemplate{
					{
						EventType:          "payment.requested",
						PartitionKeyPolicy: "inherit",
						DataTemplate: map[string]string{
							"payment_id": "{{new_id}}",
							"order_id": "{{$.order_id}}",
							"customer_id": "{{$.customer_id}}",
							"amount": "{{$.total_amount}}",
							"currency": "{{$.currency}}",
							"payment_method": "card",
							"created_at": "{{now}}",
						},
					},
				},
			},
			{
				ID:       "free_order",
				Priority: 50,
				Condition: func(payload map[string]any) bool {
					val, ok := getFloat64(payload, "total_amount"); ok && val == 0
				},
				Effects: []EffectTemplate{
					{
						EventType:          "order.confirmed",
						PartitionKeyPolicy: "inherit",
						DataTemplate: map[string]string{
							"order_id": "{{$.order_id}}",
							"customer_id": "{{$.customer_id}}",
							"confirmed_at": "{{now}}",
						},
					},
				},
			},
		},
	}
}

// Evaluate runs all rules against the payload and returns matching effects
func (e *Evaluator) Evaluate(payload *order_created.Created) ([]Effect, error) {
	// Convert payload to map for evaluation
	data, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	var payloadMap map[string]any
	if err := json.Unmarshal(data, &payloadMap); err != nil {
		return nil, err
	}

	var effects []Effect
	for _, rule := range e.rules {
		if rule.Condition(payloadMap) {
			for _, effTmpl := range rule.Effects {
				effect := Effect{
					Type:          effTmpl.EventType,
					PartitionKey:  computePartitionKey(payloadMap, effTmpl.PartitionKeyPolicy),
				}
				effect.Payload = substituteTemplate(effTmpl.DataTemplate, payloadMap)
				effects = append(effects, effect)
			}
		}
	}
	return effects, nil
}

func getFloat64(m map[string]any, key string) (float64, bool) {
	switch v := m[key].(type) {
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int64:
		return float64(v), true
	case json.Number:
		f, _ := v.Float64()
		return f, true
	}
	return 0, false
}

func getString(m map[string]any, key string) (string, bool) {
	v, ok := m[key]
	if !ok {
		return "", false
	}
	switch v := v.(type) {
	case string:
		return v, true
	case json.Number:
		return v.String(), true
	}
	return fmt.Sprintf("%v", v), true
}

func computePartitionKey(payload map[string]any, policy string) string {
	switch policy {
	case "inherit":
		if pk, ok := getString(payload, "customer_id"); ok {
			return pk
		}
		if pk, ok := getString(payload, "partition_key"); ok {
			return pk
		}
		return "default"
	default:
		return policy
	}
}

func substituteTemplate(tmpl map[string]string, payload map[string]any) map[string]any {
	result := make(map[string]any)
	for k, v := range tmpl {
		result[k] = substituteValue(v, payload)
	}
	return result
}

func substituteValue(val string, payload map[string]any) any {
	val = strings.TrimSpace(val)
	
	if val == "{{new_id}}" {
		return domain.NewID()
	}
	if val == "{{now}}" {
		return time.Now().UTC().Format(time.RFC3339)
	}
	
	if strings.HasPrefix(val, "{{$.") && strings.HasSuffix(val, "}}") {
		key := strings.TrimPrefix(val, "{{$.")
		key = strings.TrimSuffix(key, "}}")
		if v, ok := payload[key]; ok {
			return v
		}
		return nil
	}
	
	if strings.HasPrefix(val, "{{") && strings.HasSuffix(val, "}}") {
		key := strings.TrimPrefix(val, "{{")
		key = strings.TrimSuffix(key, "}}")
		if v, ok := payload[key]; ok {
			return v
		}
		return nil
	}
	
	return val
}
