// Code generated by FlowRule. DO NOT EDIT.

package runtime

import (
	"context"
	"encoding/json"

	"github.com/nats-io/nats.go/jetstream"
)

// Publisher handles publishing order.created events
type Publisher struct {
	js        jetstream.JetStream
	stream    string
	numShards uint32
}

// NewPublisher creates a new publisher for order.created
func NewPublisher(js jetstream.JetStream, stream string, numShards uint32) *Publisher {
	return &Publisher{
		js:        js,
		stream:    stream,
		numShards: numShards,
	}
}

// Publish publishes a order.created event
func (p *Publisher) Publish(ctx context.Context, payload *order_created.Created, tenantID, partitionKey string) error {
	env := NewEnvelope(payload, tenantID, partitionKey)
	data, err := json.Marshal(env)
	if err != nil {
		return err
	}

	shard := env.Shard(p.numShards)
	subject := "events.shard." + string(rune('0'+shard%10))

	_, err = p.js.Publish(ctx, subject, data)
	return err
}

// PublishToShard publishes to a specific shard
func (p *Publisher) PublishToShard(ctx context.Context, payload *order_created.Created, tenantID, partitionKey string, shard uint32) error {
	env := NewEnvelope(payload, tenantID, partitionKey)
	data, err := json.Marshal(env)
	if err != nil {
		return err
	}

	subject := "events.shard." + string(rune('0'+shard%10))
	_, err = p.js.Publish(ctx, subject, data)
	return err
}
