// Code generated by FlowRule. DO NOT EDIT.

package runtime

import (
	"context"
	"fmt"

	"github.com/nats-io/nats.go/jetstream"
)

// Service wires together consumer, evaluator, and publishers for order.created
type Service struct {
	consumer   *Consumer
	evaluator  *Evaluator
	publishers map[string]*Publisher
	js         jetstream.JetStream
	stream     string
	numShards  uint32
)

// ServiceConfig holds configuration for the service
type ServiceConfig struct {
	JS        jetstream.JetStream
	Stream    string
	Consumer  string
	NumShards uint32
	Handler   func(ctx context.Context, eventType string, payload any, envelope *Envelope) error
}

// NewService creates a new service for order.created
func NewService(config ServiceConfig) *Service {
	if config.NumShards == 0 {
		config.NumShards = 4096
	}

	s := &Service{
		consumer:   NewConsumer(config.JS, config.Stream, config.Consumer, config.NumShards, s.handleEvent),
		evaluator:  NewEvaluator(),
		publishers: make(map[string]*Publisher),
		js:         config.JS,
		stream:     config.Stream,
		numShards:  config.NumShards,
	}

	// Create publishers for all output event types
	s.publishers["payment.requested"] = NewPublisher(config.JS, config.Stream, config.NumShards)
	s.publishers["order.confirmed"] = NewPublisher(config.JS, config.Stream, config.NumShards)

	return s
}

// Start begins processing events
func (s *Service) Start(ctx context.Context) error {
	return s.consumer.Start(ctx)
}

// handleEvent processes incoming events through the evaluator and publishes effects
func (s *Service) handleEvent(ctx context.Context, payload *order_created.Created, envelope *Envelope) error {
	effects, err := s.evaluator.Evaluate(payload)
	if err != nil {
		return fmt.Errorf("evaluate: %w", err)
	}

	for _, effect := range effects {
		publisher, ok := s.publishers[effect.Type]
		if !ok {
			// Publisher not configured for this effect type
			continue
		}

		partitionKey := effect.PartitionKey
		if partitionKey == "" && envelope != nil {
			partitionKey = envelope.PartitionKey
		}

		if err := publisher.Publish(ctx, effect.Payload, envelope.TenantID, partitionKey); err != nil {
			return fmt.Errorf("publish %s: %w", effect.Type, err)
		}
	}

	return nil
}
