// Code generated by FlowRule. DO NOT EDIT.

package order.created

// Event emitted when a new order is created
// Created represents the order.created contract v1.0
type Created struct {
	created_at string `json:"created_at"`
	order_id string `json:"order_id"`
	customer_id string `json:"customer_id"`
	total_amount float64 `json:"total_amount"`
	currency string `json:"currency"`
	items []interface{} `json:"items"`
	shipping_address map[string]interface{} `json:"shipping_address"`
}
